[build]
  publish = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 